name: database_adapter_mysql
version: 0.2.0
description: An adapter for using 'package:database' API with a PostgreSQL database.
homepage: https://github.com/dint-dev/database
publish_to: none

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  collection: ^1.14.0
  database:
    git:
      url: https://github.com/odunboye/database/
      path: database
  meta: ^1.1.0
  mysql1:
    git: https://github.com/adamlofts/mysql1_dart

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.8.0
