name: kind
description: Powerful JSON serialization, database-object mapping, test data generation, and more.
  Describe your data model with Kind<T> subclasses (such as IntKind, ListKind<T>, etc.).
version: 0.6.0
homepage: https://github.com/dint-dev/database

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  collection: ^1.17.2
  meta: ^1.9.1
  os: ^1.0.1

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.3